version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - FRONTEND_URL=http://localhost:5173
      - BACKEND_URL=http://localhost:8000
    volumes:
      - ./api:/app/api
      - /app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend